# Определение версии Docker Compose и начало описания сервисов
version: '3'

services:
  django:
    container_name: beeline
    build: .
    command: bash -c "python /usr/src/beeline/manage.py migrate --noinput && 
                      python /usr/src/beeline/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/beeline
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    # Использование готового образа postgres
    image: postgres
    # Задание переменных окружения для контейнера с postgres
    environment:
      POSTGRES_PASSWORD: postgres
     # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: